//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Biome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Biome() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Resources.Biome", typeof(Biome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:beaches 的本地化字符串。
        /// </summary>
        public static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:birch_forest 的本地化字符串。
        /// </summary>
        public static string Birch_Forest {
            get {
                return ResourceManager.GetString("Birch_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:birch_forest_hills 的本地化字符串。
        /// </summary>
        public static string Birch_Forest_Hills {
            get {
                return ResourceManager.GetString("Birch_Forest_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_birch_forest_hills 的本地化字符串。
        /// </summary>
        public static string Birch_Forest_Hills_M {
            get {
                return ResourceManager.GetString("Birch_Forest_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_birch_forest 的本地化字符串。
        /// </summary>
        public static string Birch_Forest_M {
            get {
                return ResourceManager.GetString("Birch_Forest_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:cold_beach 的本地化字符串。
        /// </summary>
        public static string Cold_Beach {
            get {
                return ResourceManager.GetString("Cold_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:taiga_cold 的本地化字符串。
        /// </summary>
        public static string Cold_Taiga {
            get {
                return ResourceManager.GetString("Cold_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:taiga_cold_hills 的本地化字符串。
        /// </summary>
        public static string Cold_Taiga_Hills {
            get {
                return ResourceManager.GetString("Cold_Taiga_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_taiga_cold 的本地化字符串。
        /// </summary>
        public static string Cold_Taiga_M {
            get {
                return ResourceManager.GetString("Cold_Taiga_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:deep_ocean 的本地化字符串。
        /// </summary>
        public static string Deep_Ocean {
            get {
                return ResourceManager.GetString("Deep_Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:desert 的本地化字符串。
        /// </summary>
        public static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_desert 的本地化字符串。
        /// </summary>
        public static string Desert_M {
            get {
                return ResourceManager.GetString("Desert_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:desert_hills 的本地化字符串。
        /// </summary>
        public static string DesertHills {
            get {
                return ResourceManager.GetString("DesertHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:extreme_hills 的本地化字符串。
        /// </summary>
        public static string Extreme_Hills {
            get {
                return ResourceManager.GetString("Extreme_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:smaller_extreme_hills 的本地化字符串。
        /// </summary>
        public static string Extreme_Hills_Edge {
            get {
                return ResourceManager.GetString("Extreme_Hills_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_extreme_hills 的本地化字符串。
        /// </summary>
        public static string Extreme_Hills_M {
            get {
                return ResourceManager.GetString("Extreme_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:extreme_hills_with_trees 的本地化字符串。
        /// </summary>
        public static string Extreme_Hills_plus {
            get {
                return ResourceManager.GetString("Extreme_Hills_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_extreme_hills_with_trees 的本地化字符串。
        /// </summary>
        public static string Extreme_Hills_plus_M {
            get {
                return ResourceManager.GetString("Extreme_Hills_plus_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_forest 的本地化字符串。
        /// </summary>
        public static string Flower_Forest {
            get {
                return ResourceManager.GetString("Flower_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:forest 的本地化字符串。
        /// </summary>
        public static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:forest_hills 的本地化字符串。
        /// </summary>
        public static string ForestHills {
            get {
                return ResourceManager.GetString("ForestHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:frozen_ocean 的本地化字符串。
        /// </summary>
        public static string FrozenOcean {
            get {
                return ResourceManager.GetString("FrozenOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:frozen_river 的本地化字符串。
        /// </summary>
        public static string FrozenRiver {
            get {
                return ResourceManager.GetString("FrozenRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:hell 的本地化字符串。
        /// </summary>
        public static string Hell {
            get {
                return ResourceManager.GetString("Hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:ice_mountains 的本地化字符串。
        /// </summary>
        public static string Ice_Mountains {
            get {
                return ResourceManager.GetString("Ice_Mountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:ice_flats 的本地化字符串。
        /// </summary>
        public static string Ice_Plains {
            get {
                return ResourceManager.GetString("Ice_Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_ice_flats 的本地化字符串。
        /// </summary>
        public static string Ice_Plains_Spikes {
            get {
                return ResourceManager.GetString("Ice_Plains_Spikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:jungle 的本地化字符串。
        /// </summary>
        public static string Jungle {
            get {
                return ResourceManager.GetString("Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_jungle 的本地化字符串。
        /// </summary>
        public static string Jungle_M {
            get {
                return ResourceManager.GetString("Jungle_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:jungle_edge 的本地化字符串。
        /// </summary>
        public static string JungleEdge {
            get {
                return ResourceManager.GetString("JungleEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_jungle_edge 的本地化字符串。
        /// </summary>
        public static string JungleEdge_M {
            get {
                return ResourceManager.GetString("JungleEdge_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:jungle_hills 的本地化字符串。
        /// </summary>
        public static string JungleHills {
            get {
                return ResourceManager.GetString("JungleHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_redwood_taiga 的本地化字符串。
        /// </summary>
        public static string Mega_Spruce_Taiga {
            get {
                return ResourceManager.GetString("Mega_Spruce_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:redwood_taiga 的本地化字符串。
        /// </summary>
        public static string Mega_Taiga {
            get {
                return ResourceManager.GetString("Mega_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:redwood_taiga_hills 的本地化字符串。
        /// </summary>
        public static string Mega_Taiga_Hills {
            get {
                return ResourceManager.GetString("Mega_Taiga_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mesa 的本地化字符串。
        /// </summary>
        public static string Mesa {
            get {
                return ResourceManager.GetString("Mesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_mesa 的本地化字符串。
        /// </summary>
        public static string Mesa_Bryce {
            get {
                return ResourceManager.GetString("Mesa_Bryce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mesa_clear_rock 的本地化字符串。
        /// </summary>
        public static string Mesa_Plateau {
            get {
                return ResourceManager.GetString("Mesa_Plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mesa_rock 的本地化字符串。
        /// </summary>
        public static string Mesa_Plateau_F {
            get {
                return ResourceManager.GetString("Mesa_Plateau_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_mesa_rock 的本地化字符串。
        /// </summary>
        public static string Mesa_Plateau_F_M {
            get {
                return ResourceManager.GetString("Mesa_Plateau_F_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_mesa_clear_rock 的本地化字符串。
        /// </summary>
        public static string Mesa_Plateau_M {
            get {
                return ResourceManager.GetString("Mesa_Plateau_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mushroom_island 的本地化字符串。
        /// </summary>
        public static string MushroomIsland {
            get {
                return ResourceManager.GetString("MushroomIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mushroom_island_shore 的本地化字符串。
        /// </summary>
        public static string MushroomIslandShore {
            get {
                return ResourceManager.GetString("MushroomIslandShore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:ocean 的本地化字符串。
        /// </summary>
        public static string Ocean {
            get {
                return ResourceManager.GetString("Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:plains 的本地化字符串。
        /// </summary>
        public static string Plains {
            get {
                return ResourceManager.GetString("Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_redwood_taiga_hills 的本地化字符串。
        /// </summary>
        public static string Redwood_Taiga_Hills_M {
            get {
                return ResourceManager.GetString("Redwood_Taiga_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:river 的本地化字符串。
        /// </summary>
        public static string River {
            get {
                return ResourceManager.GetString("River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:roofed_forest 的本地化字符串。
        /// </summary>
        public static string Roofed_Forest {
            get {
                return ResourceManager.GetString("Roofed_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_roofed_forest 的本地化字符串。
        /// </summary>
        public static string Roofed_Forest_M {
            get {
                return ResourceManager.GetString("Roofed_Forest_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:savanna 的本地化字符串。
        /// </summary>
        public static string Savanna {
            get {
                return ResourceManager.GetString("Savanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_savanna 的本地化字符串。
        /// </summary>
        public static string Savanna_M {
            get {
                return ResourceManager.GetString("Savanna_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:savanna_rock 的本地化字符串。
        /// </summary>
        public static string Savanna_Plateau {
            get {
                return ResourceManager.GetString("Savanna_Plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_savanna_rock 的本地化字符串。
        /// </summary>
        public static string Savanna_Plateau_M {
            get {
                return ResourceManager.GetString("Savanna_Plateau_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:stone_beach 的本地化字符串。
        /// </summary>
        public static string Stone_Beach {
            get {
                return ResourceManager.GetString("Stone_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_plains 的本地化字符串。
        /// </summary>
        public static string Sunflower_Plains {
            get {
                return ResourceManager.GetString("Sunflower_Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:swampland 的本地化字符串。
        /// </summary>
        public static string Swampland {
            get {
                return ResourceManager.GetString("Swampland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_swampland 的本地化字符串。
        /// </summary>
        public static string Swampland_M {
            get {
                return ResourceManager.GetString("Swampland_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:taiga 的本地化字符串。
        /// </summary>
        public static string Taiga {
            get {
                return ResourceManager.GetString("Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:mutated_taiga 的本地化字符串。
        /// </summary>
        public static string Taiga_M {
            get {
                return ResourceManager.GetString("Taiga_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:taiga_hills 的本地化字符串。
        /// </summary>
        public static string TaigaHills {
            get {
                return ResourceManager.GetString("TaigaHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:sky 的本地化字符串。
        /// </summary>
        public static string The_End {
            get {
                return ResourceManager.GetString("The_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:void 的本地化字符串。
        /// </summary>
        public static string The_Void {
            get {
                return ResourceManager.GetString("The_Void", resourceCulture);
            }
        }
    }
}
