//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BiomeDescribe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BiomeDescribe() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Resources.BiomeDescribe", typeof(BiomeDescribe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 沙滩 的本地化字符串。
        /// </summary>
        internal static string Beach {
            get {
                return ResourceManager.GetString("Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桦木森林 的本地化字符串。
        /// </summary>
        internal static string Birch_Forest {
            get {
                return ResourceManager.GetString("Birch_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桦木森林山丘 的本地化字符串。
        /// </summary>
        internal static string Birch_Forest_Hills {
            get {
                return ResourceManager.GetString("Birch_Forest_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桦木森林山丘 M 的本地化字符串。
        /// </summary>
        internal static string Birch_Forest_Hills_M {
            get {
                return ResourceManager.GetString("Birch_Forest_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桦木森林 M 的本地化字符串。
        /// </summary>
        internal static string Birch_Forest_M {
            get {
                return ResourceManager.GetString("Birch_Forest_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寒冷沙滩 的本地化字符串。
        /// </summary>
        internal static string Cold_Beach {
            get {
                return ResourceManager.GetString("Cold_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷针叶林 的本地化字符串。
        /// </summary>
        internal static string Cold_Taiga {
            get {
                return ResourceManager.GetString("Cold_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷针叶林山丘 的本地化字符串。
        /// </summary>
        internal static string Cold_Taiga_Hills {
            get {
                return ResourceManager.GetString("Cold_Taiga_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷针叶林 M 的本地化字符串。
        /// </summary>
        internal static string Cold_Taiga_M {
            get {
                return ResourceManager.GetString("Cold_Taiga_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深海 的本地化字符串。
        /// </summary>
        internal static string Deep_Ocean {
            get {
                return ResourceManager.GetString("Deep_Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漠 的本地化字符串。
        /// </summary>
        internal static string Desert {
            get {
                return ResourceManager.GetString("Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漠 M 的本地化字符串。
        /// </summary>
        internal static string Desert_M {
            get {
                return ResourceManager.GetString("Desert_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沙漠山丘 的本地化字符串。
        /// </summary>
        internal static string DesertHills {
            get {
                return ResourceManager.GetString("DesertHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 峭壁 的本地化字符串。
        /// </summary>
        internal static string Extreme_Hills {
            get {
                return ResourceManager.GetString("Extreme_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬崖 的本地化字符串。
        /// </summary>
        internal static string Extreme_Hills_Edge {
            get {
                return ResourceManager.GetString("Extreme_Hills_Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 峭壁 M 的本地化字符串。
        /// </summary>
        internal static string Extreme_Hills_M {
            get {
                return ResourceManager.GetString("Extreme_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 峭壁+ 的本地化字符串。
        /// </summary>
        internal static string Extreme_Hills_plus {
            get {
                return ResourceManager.GetString("Extreme_Hills_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 峭壁+ M 的本地化字符串。
        /// </summary>
        internal static string Extreme_Hills_plus_M {
            get {
                return ResourceManager.GetString("Extreme_Hills_plus_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁花森林 的本地化字符串。
        /// </summary>
        internal static string Flower_Forest {
            get {
                return ResourceManager.GetString("Flower_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 森林 的本地化字符串。
        /// </summary>
        internal static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 森林山丘 的本地化字符串。
        /// </summary>
        internal static string ForestHills {
            get {
                return ResourceManager.GetString("ForestHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻洋 的本地化字符串。
        /// </summary>
        internal static string FrozenOcean {
            get {
                return ResourceManager.GetString("FrozenOcean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻河 的本地化字符串。
        /// </summary>
        internal static string FrozenRiver {
            get {
                return ResourceManager.GetString("FrozenRiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地狱 的本地化字符串。
        /// </summary>
        internal static string Hell {
            get {
                return ResourceManager.GetString("Hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雪山 的本地化字符串。
        /// </summary>
        internal static string Ice_Mountains {
            get {
                return ResourceManager.GetString("Ice_Mountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰原 的本地化字符串。
        /// </summary>
        internal static string Ice_Plains {
            get {
                return ResourceManager.GetString("Ice_Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰刺平原 的本地化字符串。
        /// </summary>
        internal static string Ice_Plains_Spikes {
            get {
                return ResourceManager.GetString("Ice_Plains_Spikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丛林 的本地化字符串。
        /// </summary>
        internal static string Jungle {
            get {
                return ResourceManager.GetString("Jungle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丛林 M 的本地化字符串。
        /// </summary>
        internal static string Jungle_M {
            get {
                return ResourceManager.GetString("Jungle_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丛林边缘 的本地化字符串。
        /// </summary>
        internal static string JungleEdge {
            get {
                return ResourceManager.GetString("JungleEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丛林边缘 M 的本地化字符串。
        /// </summary>
        internal static string JungleEdge_M {
            get {
                return ResourceManager.GetString("JungleEdge_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 丛林山丘 的本地化字符串。
        /// </summary>
        internal static string JungleHills {
            get {
                return ResourceManager.GetString("JungleHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红木森林 的本地化字符串。
        /// </summary>
        internal static string Mega_Spruce_Taiga {
            get {
                return ResourceManager.GetString("Mega_Spruce_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型针叶林 的本地化字符串。
        /// </summary>
        internal static string Mega_Taiga {
            get {
                return ResourceManager.GetString("Mega_Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型针叶林山丘 的本地化字符串。
        /// </summary>
        internal static string Mega_Taiga_Hills {
            get {
                return ResourceManager.GetString("Mega_Taiga_Hills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山 的本地化字符串。
        /// </summary>
        internal static string Mesa {
            get {
                return ResourceManager.GetString("Mesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山（岩柱） 的本地化字符串。
        /// </summary>
        internal static string Mesa_Bryce {
            get {
                return ResourceManager.GetString("Mesa_Bryce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山高原 的本地化字符串。
        /// </summary>
        internal static string Mesa_Plateau {
            get {
                return ResourceManager.GetString("Mesa_Plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山高原 F 的本地化字符串。
        /// </summary>
        internal static string Mesa_Plateau_F {
            get {
                return ResourceManager.GetString("Mesa_Plateau_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山高原 F M 的本地化字符串。
        /// </summary>
        internal static string Mesa_Plateau_F_M {
            get {
                return ResourceManager.GetString("Mesa_Plateau_F_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平顶山高原 M 的本地化字符串。
        /// </summary>
        internal static string Mesa_Plateau_M {
            get {
                return ResourceManager.GetString("Mesa_Plateau_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蘑菇岛 的本地化字符串。
        /// </summary>
        internal static string MushroomIsland {
            get {
                return ResourceManager.GetString("MushroomIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蘑菇岛岸 的本地化字符串。
        /// </summary>
        internal static string MushroomIslandShore {
            get {
                return ResourceManager.GetString("MushroomIslandShore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海洋 的本地化字符串。
        /// </summary>
        internal static string Ocean {
            get {
                return ResourceManager.GetString("Ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草原 的本地化字符串。
        /// </summary>
        internal static string Plains {
            get {
                return ResourceManager.GetString("Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红木山丘 的本地化字符串。
        /// </summary>
        internal static string Redwood_Taiga_Hills_M {
            get {
                return ResourceManager.GetString("Redwood_Taiga_Hills_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 河流 的本地化字符串。
        /// </summary>
        internal static string River {
            get {
                return ResourceManager.GetString("River", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑森林 的本地化字符串。
        /// </summary>
        internal static string Roofed_Forest {
            get {
                return ResourceManager.GetString("Roofed_Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黑森林 M 的本地化字符串。
        /// </summary>
        internal static string Roofed_Forest_M {
            get {
                return ResourceManager.GetString("Roofed_Forest_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热带草原 的本地化字符串。
        /// </summary>
        internal static string Savanna {
            get {
                return ResourceManager.GetString("Savanna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热带草原 M 的本地化字符串。
        /// </summary>
        internal static string Savanna_M {
            get {
                return ResourceManager.GetString("Savanna_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热带高原 的本地化字符串。
        /// </summary>
        internal static string Savanna_Plateau {
            get {
                return ResourceManager.GetString("Savanna_Plateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热带高原 M 的本地化字符串。
        /// </summary>
        internal static string Savanna_Plateau_M {
            get {
                return ResourceManager.GetString("Savanna_Plateau_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 石滩 的本地化字符串。
        /// </summary>
        internal static string Stone_Beach {
            get {
                return ResourceManager.GetString("Stone_Beach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向日葵草原 的本地化字符串。
        /// </summary>
        internal static string Sunflower_Plains {
            get {
                return ResourceManager.GetString("Sunflower_Plains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沼泽 的本地化字符串。
        /// </summary>
        internal static string Swampland {
            get {
                return ResourceManager.GetString("Swampland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沼泽 M 的本地化字符串。
        /// </summary>
        internal static string Swampland_M {
            get {
                return ResourceManager.GetString("Swampland_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 针叶林 的本地化字符串。
        /// </summary>
        internal static string Taiga {
            get {
                return ResourceManager.GetString("Taiga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 针叶林 M 的本地化字符串。
        /// </summary>
        internal static string Taiga_M {
            get {
                return ResourceManager.GetString("Taiga_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 针叶林山丘 的本地化字符串。
        /// </summary>
        internal static string TaigaHills {
            get {
                return ResourceManager.GetString("TaigaHills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末路之地 的本地化字符串。
        /// </summary>
        internal static string The_End {
            get {
                return ResourceManager.GetString("The_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚空 的本地化字符串。
        /// </summary>
        internal static string The_Void {
            get {
                return ResourceManager.GetString("The_Void", resourceCulture);
            }
        }
    }
}
