//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PotionDescribe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PotionDescribe() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Resources.PotionDescribe", typeof(PotionDescribe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 粗制的药水 的本地化字符串。
        /// </summary>
        public static string Awkward_Potion {
            get {
                return ResourceManager.GetString("Awkward_Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗火 的本地化字符串。
        /// </summary>
        public static string Fire_Resistance {
            get {
                return ResourceManager.GetString("Fire_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害 的本地化字符串。
        /// </summary>
        public static string Harming {
            get {
                return ResourceManager.GetString("Harming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害II 的本地化字符串。
        /// </summary>
        public static string Harming_II {
            get {
                return ResourceManager.GetString("Harming_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗 的本地化字符串。
        /// </summary>
        public static string Instant_Health {
            get {
                return ResourceManager.GetString("Instant_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 治疗II 的本地化字符串。
        /// </summary>
        public static string Instant_Health_II {
            get {
                return ResourceManager.GetString("Instant_Health_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身 的本地化字符串。
        /// </summary>
        public static string Invisibility {
            get {
                return ResourceManager.GetString("Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳跃 的本地化字符串。
        /// </summary>
        public static string Leaping {
            get {
                return ResourceManager.GetString("Leaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳跃II 的本地化字符串。
        /// </summary>
        public static string Leaping_II {
            get {
                return ResourceManager.GetString("Leaping_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抗火-延长 的本地化字符串。
        /// </summary>
        public static string Long_Fire_Resistance {
            get {
                return ResourceManager.GetString("Long_Fire_Resistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身-延长 的本地化字符串。
        /// </summary>
        public static string Long_Invisibility {
            get {
                return ResourceManager.GetString("Long_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳跃-延长 的本地化字符串。
        /// </summary>
        public static string Long_Leaping {
            get {
                return ResourceManager.GetString("Long_Leaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜视-延长 的本地化字符串。
        /// </summary>
        public static string Long_Night_Vision {
            get {
                return ResourceManager.GetString("Long_Night_Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中毒-延长 的本地化字符串。
        /// </summary>
        public static string Long_Poison {
            get {
                return ResourceManager.GetString("Long_Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生-延长 的本地化字符串。
        /// </summary>
        public static string Long_Regeneration {
            get {
                return ResourceManager.GetString("Long_Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓慢-延长 的本地化字符串。
        /// </summary>
        public static string Long_Slowness {
            get {
                return ResourceManager.GetString("Long_Slowness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力量-延长 的本地化字符串。
        /// </summary>
        public static string Long_Strength {
            get {
                return ResourceManager.GetString("Long_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迅捷-延长 的本地化字符串。
        /// </summary>
        public static string Long_Swiftness {
            get {
                return ResourceManager.GetString("Long_Swiftness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水下呼吸-延长 的本地化字符串。
        /// </summary>
        public static string Long_Water_Breathing {
            get {
                return ResourceManager.GetString("Long_Water_Breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚弱-延长 的本地化字符串。
        /// </summary>
        public static string Long_Weakness {
            get {
                return ResourceManager.GetString("Long_Weakness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 幸运 的本地化字符串。
        /// </summary>
        public static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平凡的药水 的本地化字符串。
        /// </summary>
        public static string Mundane_Potion {
            get {
                return ResourceManager.GetString("Mundane_Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜视 的本地化字符串。
        /// </summary>
        public static string Night_Vision {
            get {
                return ResourceManager.GetString("Night_Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中毒 的本地化字符串。
        /// </summary>
        public static string Poison {
            get {
                return ResourceManager.GetString("Poison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中毒II 的本地化字符串。
        /// </summary>
        public static string Poison_II {
            get {
                return ResourceManager.GetString("Poison_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生 的本地化字符串。
        /// </summary>
        public static string Regeneration {
            get {
                return ResourceManager.GetString("Regeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生II 的本地化字符串。
        /// </summary>
        public static string Regeneration_II {
            get {
                return ResourceManager.GetString("Regeneration_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓慢 的本地化字符串。
        /// </summary>
        public static string Slowness {
            get {
                return ResourceManager.GetString("Slowness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力量 的本地化字符串。
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 力量II 的本地化字符串。
        /// </summary>
        public static string Strength_II {
            get {
                return ResourceManager.GetString("Strength_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迅捷 的本地化字符串。
        /// </summary>
        public static string Swiftness {
            get {
                return ResourceManager.GetString("Swiftness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 迅捷II 的本地化字符串。
        /// </summary>
        public static string Swiftness_II {
            get {
                return ResourceManager.GetString("Swiftness_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浑浊的药水 的本地化字符串。
        /// </summary>
        public static string Thick_Potion {
            get {
                return ResourceManager.GetString("Thick_Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水瓶 的本地化字符串。
        /// </summary>
        public static string Water_Bottle {
            get {
                return ResourceManager.GetString("Water_Bottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水下呼吸 的本地化字符串。
        /// </summary>
        public static string Water_Breathing {
            get {
                return ResourceManager.GetString("Water_Breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚弱 的本地化字符串。
        /// </summary>
        public static string Weakness {
            get {
                return ResourceManager.GetString("Weakness", resourceCulture);
            }
        }
    }
}
