//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trigger {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trigger() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Resources.Trigger", typeof(Trigger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:bred_animals 的本地化字符串。
        /// </summary>
        public static string bred_animals {
            get {
                return ResourceManager.GetString("bred_animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:brewed_potion 的本地化字符串。
        /// </summary>
        public static string brewed_potion {
            get {
                return ResourceManager.GetString("brewed_potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:changed_dimension 的本地化字符串。
        /// </summary>
        public static string changed_dimension {
            get {
                return ResourceManager.GetString("changed_dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:construct_beacon 的本地化字符串。
        /// </summary>
        public static string construct_beacon {
            get {
                return ResourceManager.GetString("construct_beacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:consume_item 的本地化字符串。
        /// </summary>
        public static string consume_item {
            get {
                return ResourceManager.GetString("consume_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:cured_zombie_villager 的本地化字符串。
        /// </summary>
        public static string cured_zombie_villager {
            get {
                return ResourceManager.GetString("cured_zombie_villager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:effects_changed 的本地化字符串。
        /// </summary>
        public static string effects_changed {
            get {
                return ResourceManager.GetString("effects_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:enchanted_item 的本地化字符串。
        /// </summary>
        public static string enchanted_item {
            get {
                return ResourceManager.GetString("enchanted_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:enter_block 的本地化字符串。
        /// </summary>
        public static string enter_block {
            get {
                return ResourceManager.GetString("enter_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:entity_hurt_player 的本地化字符串。
        /// </summary>
        public static string entity_hurt_player {
            get {
                return ResourceManager.GetString("entity_hurt_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:entity_killed_player 的本地化字符串。
        /// </summary>
        public static string entity_killed_player {
            get {
                return ResourceManager.GetString("entity_killed_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:impossible 的本地化字符串。
        /// </summary>
        public static string impossible {
            get {
                return ResourceManager.GetString("impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:inventory_changed 的本地化字符串。
        /// </summary>
        public static string inventory_changed {
            get {
                return ResourceManager.GetString("inventory_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:item_durability_changed 的本地化字符串。
        /// </summary>
        public static string item_durability_changed {
            get {
                return ResourceManager.GetString("item_durability_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:levitation 的本地化字符串。
        /// </summary>
        public static string levitation {
            get {
                return ResourceManager.GetString("levitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:location 的本地化字符串。
        /// </summary>
        public static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:nether_travel 的本地化字符串。
        /// </summary>
        public static string nether_travel {
            get {
                return ResourceManager.GetString("nether_travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:placed_block 的本地化字符串。
        /// </summary>
        public static string placed_block {
            get {
                return ResourceManager.GetString("placed_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:player_hurt_entity 的本地化字符串。
        /// </summary>
        public static string player_hurt_entity {
            get {
                return ResourceManager.GetString("player_hurt_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:player_killed_entity 的本地化字符串。
        /// </summary>
        public static string player_killed_entity {
            get {
                return ResourceManager.GetString("player_killed_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:recipe_unlocked 的本地化字符串。
        /// </summary>
        public static string recipe_unlocked {
            get {
                return ResourceManager.GetString("recipe_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:slept_in_bed 的本地化字符串。
        /// </summary>
        public static string slept_in_bed {
            get {
                return ResourceManager.GetString("slept_in_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:summoned_entity 的本地化字符串。
        /// </summary>
        public static string summoned_entity {
            get {
                return ResourceManager.GetString("summoned_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:tame_animal 的本地化字符串。
        /// </summary>
        public static string tame_animal {
            get {
                return ResourceManager.GetString("tame_animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:tick 的本地化字符串。
        /// </summary>
        public static string tick {
            get {
                return ResourceManager.GetString("tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:used_ender_eye 的本地化字符串。
        /// </summary>
        public static string used_ender_eye {
            get {
                return ResourceManager.GetString("used_ender_eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:used_totem 的本地化字符串。
        /// </summary>
        public static string used_totem {
            get {
                return ResourceManager.GetString("used_totem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 minecraft:villager_trade 的本地化字符串。
        /// </summary>
        public static string villager_trade {
            get {
                return ResourceManager.GetString("villager_trade", resourceCulture);
            }
        }
    }
}
