//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditFormUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditFormUIResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Properties.EditFormUIResources", typeof(EditFormUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实体到玩家的绝对距离 的本地化字符串。
        /// </summary>
        public static string E_Distance_absolute {
            get {
                return ResourceManager.GetString("E_Distance_absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体到玩家的水平距离 的本地化字符串。
        /// </summary>
        public static string E_Distance_horizontal {
            get {
                return ResourceManager.GetString("E_Distance_horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体到玩家的距离 的本地化字符串。
        /// </summary>
        public static string E_Distance_int {
            get {
                return ResourceManager.GetString("E_Distance_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体到玩家的距离的详细内容 的本地化字符串。
        /// </summary>
        public static string E_Distance_str {
            get {
                return ResourceManager.GetString("E_Distance_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑效果信息 的本地化字符串。
        /// </summary>
        public static string Edit_Effects {
            get {
                return ResourceManager.GetString("Edit_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑实体信息 的本地化字符串。
        /// </summary>
        public static string Edit_Entity {
            get {
                return ResourceManager.GetString("Edit_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑伤害信息 的本地化字符串。
        /// </summary>
        public static string Edit_Hurt {
            get {
                return ResourceManager.GetString("Edit_Hurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑物品信息 的本地化字符串。
        /// </summary>
        public static string Edit_Item {
            get {
                return ResourceManager.GetString("Edit_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑位置信息 的本地化字符串。
        /// </summary>
        public static string Edit_Location {
            get {
                return ResourceManager.GetString("Edit_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体药水效果 的本地化字符串。
        /// </summary>
        public static string Entity_Effects {
            get {
                return ResourceManager.GetString("Entity_Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体位置信息 的本地化字符串。
        /// </summary>
        public static string Entity_Location {
            get {
                return ResourceManager.GetString("Entity_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体NBT 的本地化字符串。
        /// </summary>
        public static string Entity_NBT {
            get {
                return ResourceManager.GetString("Entity_NBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体ID 的本地化字符串。
        /// </summary>
        public static string Entity_type {
            get {
                return ResourceManager.GetString("Entity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体所在生物群系 的本地化字符串。
        /// </summary>
        public static string Location_Biome {
            get {
                return ResourceManager.GetString("Location_Biome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体所在维度 的本地化字符串。
        /// </summary>
        public static string Location_Dimension {
            get {
                return ResourceManager.GetString("Location_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体所在结构名称 的本地化字符串。
        /// </summary>
        public static string Location_Feature {
            get {
                return ResourceManager.GetString("Location_Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体所在坐标 的本地化字符串。
        /// </summary>
        public static string Location_Position {
            get {
                return ResourceManager.GetString("Location_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
    }
}
