//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 意外的触发器序号。 的本地化字符串。
        /// </summary>
        public static string AccidentalOrder {
            get {
                return ResourceManager.GetString("AccidentalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误！ 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的生物群系序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorBiomeOrder {
            get {
                return ResourceManager.GetString("ErrorBiomeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的效果序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorEffectOrder {
            get {
                return ResourceManager.GetString("ErrorEffectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的实体序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorEntityOrder {
            get {
                return ResourceManager.GetString("ErrorEntityOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的结构序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorFeatureOrder {
            get {
                return ResourceManager.GetString("ErrorFeatureOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的边框序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorFrameOrder {
            get {
                return ResourceManager.GetString("ErrorFrameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的触发器序号！ 的本地化字符串。
        /// </summary>
        public static string ErrorTriggerOrder {
            get {
                return ResourceManager.GetString("ErrorTriggerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验需为正整数！ 的本地化字符串。
        /// </summary>
        public static string NoIntExperience {
            get {
                return ResourceManager.GetString("NoIntExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选中一项！ 的本地化字符串。
        /// </summary>
        public static string NoIsChecked {
            get {
                return ResourceManager.GetString("NoIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的触发器类型！ 的本地化字符串。
        /// </summary>
        public static string NoSelTrigger {
            get {
                return ResourceManager.GetString("NoSelTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择相应的触发器类型！ 的本地化字符串。
        /// </summary>
        public static string NoSelTriggerInfo {
            get {
                return ResourceManager.GetString("NoSelTriggerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入整型数值！ 的本地化字符串。
        /// </summary>
        public static string NotInt {
            get {
                return ResourceManager.GetString("NotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式装换不成功，经验必须为正整数！ 的本地化字符串。
        /// </summary>
        public static string NotSuccess {
            get {
                return ResourceManager.GetString("NotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置成功！ 的本地化字符串。
        /// </summary>
        public static string ResetSuccess {
            get {
                return ResourceManager.GetString("ResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
    }
}
