//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minecraft_Visual_Programming.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Minecraft_Visual_Programming.Properties.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在完成此进度后广播此信息 的本地化字符串。
        /// </summary>
        public static string Announce_to_chat {
            get {
                return ResourceManager.GetString("Announce_to_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景(可选) 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除触发器 的本地化字符串。
        /// </summary>
        public static string ClearTrigger {
            get {
                return ResourceManager.GetString("ClearTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取最大最小值 的本地化字符串。
        /// </summary>
        public static string Click_For_MIN_MAX {
            get {
                return ResourceManager.GetString("Click_For_MIN_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成实体 的本地化字符串。
        /// </summary>
        public static string CreateEntity {
            get {
                return ResourceManager.GetString("CreateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;source_entity&quot;: 
        ///{
        ///&quot;type&quot;: &quot;skeleton&quot;
        ///},
        ///&quot;direct_entity&quot;: 
        ///{
        ///&quot;type&quot;: &quot;arrow&quot;
        ///},
        ///&quot;taken&quot;: 
        ///{
        ///&quot;min&quot;: 4.0
        ///} 的本地化字符串。
        /// </summary>
        public static string DamageExample {
            get {
                return ResourceManager.GetString("DamageExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度的描述(JSON文本请直接粘贴) 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑触发器 的本地化字符串。
        /// </summary>
        public static string EditTrigger {
            get {
                return ResourceManager.GetString("EditTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置药水效果 的本地化字符串。
        /// </summary>
        public static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度图标边框 的本地化字符串。
        /// </summary>
        public static string Frame {
            get {
                return ResourceManager.GetString("Frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直到完成进度前在进度屏幕隐藏进度 的本地化字符串。
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品ID 的本地化字符串。
        /// </summary>
        public static string I_BlockOrItem {
            get {
                return ResourceManager.GetString("I_BlockOrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品数据值(可选) 的本地化字符串。
        /// </summary>
        public static string I_Data {
            get {
                return ResourceManager.GetString("I_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度的图标 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根进度 的本地化字符串。
        /// </summary>
        public static string isRoot {
            get {
                return ResourceManager.GetString("isRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置位置信息 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        public static string MAX {
            get {
                return ResourceManager.GetString("MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        public static string MIN {
            get {
                return ResourceManager.GetString("MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置最小值及最大值 的本地化字符串。
        /// </summary>
        public static string MinAndMax {
            get {
                return ResourceManager.GetString("MinAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Visual Programming 的本地化字符串。
        /// </summary>
        public static string MVPname {
            get {
                return ResourceManager.GetString("MVPname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新工程 的本地化字符串。
        /// </summary>
        public static string NewOne {
            get {
                return ResourceManager.GetString("NewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此进度的父目录(可选) 的本地化字符串。
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入方块ID 的本地化字符串。
        /// </summary>
        public static string PleaseEnterBlockInfo {
            get {
                return ResourceManager.GetString("PleaseEnterBlockInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入
        ///(实体NBT,药水NBT,物品NBT,位置信息等) 的本地化字符串。
        /// </summary>
        public static string PleaseEnterInfo {
            get {
                return ResourceManager.GetString("PleaseEnterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入整型数值 的本地化字符串。
        /// </summary>
        public static string PleaseEnterInt {
            get {
                return ResourceManager.GetString("PleaseEnterInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入状态信息(格式例如:&quot;type&quot;: &quot;allium&quot;) 的本地化字符串。
        /// </summary>
        public static string PleaseEnterStateInfo {
            get {
                return ResourceManager.GetString("PleaseEnterStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验值 的本地化字符串。
        /// </summary>
        public static string R_Experience {
            get {
                return ResourceManager.GetString("R_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行函数 的本地化字符串。
        /// </summary>
        public static string R_Function {
            get {
                return ResourceManager.GetString("R_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战利品表 的本地化字符串。
        /// </summary>
        public static string R_Loot {
            get {
                return ResourceManager.GetString("R_Loot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方列表 的本地化字符串。
        /// </summary>
        public static string R_Recipes {
            get {
                return ResourceManager.GetString("R_Recipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方 的本地化字符串。
        /// </summary>
        public static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度达成奖励 的本地化字符串。
        /// </summary>
        public static string Rewards {
            get {
                return ResourceManager.GetString("Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string Select_all {
            get {
                return ResourceManager.GetString("Select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择触发器 的本地化字符串。
        /// </summary>
        public static string SelTrigger {
            get {
                return ResourceManager.GetString("SelTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在完成此进度后显示提示信息 的本地化字符串。
        /// </summary>
        public static string Show_toast {
            get {
                return ResourceManager.GetString("Show_toast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果放大器 的本地化字符串。
        /// </summary>
        public static string T_Amplifier {
            get {
                return ResourceManager.GetString("T_Amplifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方块状态 的本地化字符串。
        /// </summary>
        public static string T_Block_state {
            get {
                return ResourceManager.GetString("T_Block_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁殖出的孩子 的本地化字符串。
        /// </summary>
        public static string T_Child {
            get {
                return ResourceManager.GetString("T_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被损耗的物品 的本地化字符串。
        /// </summary>
        public static string T_Consume_item {
            get {
                return ResourceManager.GetString("T_Consume_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离 的本地化字符串。
        /// </summary>
        public static string T_distance {
            get {
                return ResourceManager.GetString("T_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对 的本地化字符串。
        /// </summary>
        public static string T_distance_absolute {
            get {
                return ResourceManager.GetString("T_distance_absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平位置 的本地化字符串。
        /// </summary>
        public static string T_distance_horizontal {
            get {
                return ResourceManager.GetString("T_distance_horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果持续时间 的本地化字符串。
        /// </summary>
        public static string T_Duration {
            get {
                return ResourceManager.GetString("T_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效果名 的本地化字符串。
        /// </summary>
        public static string T_effect_name {
            get {
                return ResourceManager.GetString("T_effect_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对玩家造成伤害 的本地化字符串。
        /// </summary>
        public static string T_EHP_damage {
            get {
                return ResourceManager.GetString("T_EHP_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死玩家的实体 的本地化字符串。
        /// </summary>
        public static string T_EKP_entity {
            get {
                return ResourceManager.GetString("T_EKP_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死玩家的伤害 的本地化字符串。
        /// </summary>
        public static string T_EKP_killingBlow {
            get {
                return ResourceManager.GetString("T_EKP_killingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被附魔的物品 的本地化字符串。
        /// </summary>
        public static string T_Enchanted_item {
            get {
                return ResourceManager.GetString("T_Enchanted_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入的方块 的本地化字符串。
        /// </summary>
        public static string T_Enter_block {
            get {
                return ResourceManager.GetString("T_Enter_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体出发的维度 的本地化字符串。
        /// </summary>
        public static string T_From {
            get {
                return ResourceManager.GetString("T_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耐久度差值 的本地化字符串。
        /// </summary>
        public static string T_IDC_Delta {
            get {
                return ResourceManager.GetString("T_IDC_Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余耐久度 的本地化字符串。
        /// </summary>
        public static string T_IDC_Durability {
            get {
                return ResourceManager.GetString("T_IDC_Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 损害前的物品 的本地化字符串。
        /// </summary>
        public static string T_IDC_item {
            get {
                return ResourceManager.GetString("T_IDC_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品列表 的本地化字符串。
        /// </summary>
        public static string T_ITC_items {
            get {
                return ResourceManager.GetString("T_ITC_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空槽位数量 的本地化字符串。
        /// </summary>
        public static string T_ITC_SEmpty {
            get {
                return ResourceManager.GetString("T_ITC_SEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满槽位数量 的本地化字符串。
        /// </summary>
        public static string T_ITC_SFull {
            get {
                return ResourceManager.GetString("T_ITC_SFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品栏 的本地化字符串。
        /// </summary>
        public static string T_ITC_slots {
            get {
                return ResourceManager.GetString("T_ITC_slots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已使用槽位数量 的本地化字符串。
        /// </summary>
        public static string T_ITC_SOccupied {
            get {
                return ResourceManager.GetString("T_ITC_SOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信标的层数 的本地化字符串。
        /// </summary>
        public static string T_Level {
            get {
                return ResourceManager.GetString("T_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附魔花费的等级 的本地化字符串。
        /// </summary>
        public static string T_Levels {
            get {
                return ResourceManager.GetString("T_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮时间 的本地化字符串。
        /// </summary>
        public static string T_Levitation_duration {
            get {
                return ResourceManager.GetString("T_Levitation_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置信息 的本地化字符串。
        /// </summary>
        public static string T_Location {
            get {
                return ResourceManager.GetString("T_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父或母 的本地化字符串。
        /// </summary>
        public static string T_Parent {
            get {
                return ResourceManager.GetString("T_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配偶 的本地化字符串。
        /// </summary>
        public static string T_Partner {
            get {
                return ResourceManager.GetString("T_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家造成的伤害 的本地化字符串。
        /// </summary>
        public static string T_PHE_damage {
            get {
                return ResourceManager.GetString("T_PHE_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家杀死的实体 的本地化字符串。
        /// </summary>
        public static string T_PKE_entity {
            get {
                return ResourceManager.GetString("T_PKE_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杀死实体的伤害 的本地化字符串。
        /// </summary>
        public static string T_PKE_killingBlow {
            get {
                return ResourceManager.GetString("T_PKE_killingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被放置的方块ID 的本地化字符串。
        /// </summary>
        public static string T_Place_block_block {
            get {
                return ResourceManager.GetString("T_Place_block_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被放置的物品 的本地化字符串。
        /// </summary>
        public static string T_Place_block_item {
            get {
                return ResourceManager.GetString("T_Place_block_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被放置的位置 的本地化字符串。
        /// </summary>
        public static string T_Place_block_location {
            get {
                return ResourceManager.GetString("T_Place_block_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个酿造药水的ID 的本地化字符串。
        /// </summary>
        public static string T_Potion {
            get {
                return ResourceManager.GetString("T_Potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 睡觉的位置 的本地化字符串。
        /// </summary>
        public static string T_SIBed_location {
            get {
                return ResourceManager.GetString("T_SIBed_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家召唤的实体 的本地化字符串。
        /// </summary>
        public static string T_Summon_entity {
            get {
                return ResourceManager.GetString("T_Summon_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家驯服的实体 的本地化字符串。
        /// </summary>
        public static string T_Tame_animal_entity {
            get {
                return ResourceManager.GetString("T_Tame_animal_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体到达的维度 的本地化字符串。
        /// </summary>
        public static string T_To {
            get {
                return ResourceManager.GetString("T_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家与要塞的水平距离 的本地化字符串。
        /// </summary>
        public static string T_UEEye_distance {
            get {
                return ResourceManager.GetString("T_UEEye_distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的村民 的本地化字符串。
        /// </summary>
        public static string T_Villager {
            get {
                return ResourceManager.GetString("T_Villager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与村民购买的物品 的本地化字符串。
        /// </summary>
        public static string T_VTrade_item {
            get {
                return ResourceManager.GetString("T_VTrade_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 售卖的村民 的本地化字符串。
        /// </summary>
        public static string T_VTrade_villager {
            get {
                return ResourceManager.GetString("T_VTrade_villager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换前的僵尸 的本地化字符串。
        /// </summary>
        public static string T_Zombie {
            get {
                return ResourceManager.GetString("T_Zombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度的名称(JSON文本请直接粘贴) 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发器输出 的本地化字符串。
        /// </summary>
        public static string TriggerOutput {
            get {
                return ResourceManager.GetString("TriggerOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip:你可以在这里直接更改文本信息 的本地化字符串。
        /// </summary>
        public static string YouCanChangeText {
            get {
                return ResourceManager.GetString("YouCanChangeText", resourceCulture);
            }
        }
    }
}
